server:
  port: 8080

eureka:
     client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: Library-Demo
        instance:
          instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
